---
# Persistent configs
tem_simulator_executable: "/home/kshin/Documents/software/TEM-simulator_1.3/src/TEM-simulator"
chimera_exec_path: "/usr/sbin/chimera"

# Run-specific configs
model: "/data/kshin/T4SS_sim/PDB/pdb_maps/barrel_chimera.mrc"
root: "/data/kshin/T4SS_sim/PDB/test"
config: "/data/kshin/T4SS_sim/PDB/test/template_files/sim.txt"
coord: "/data/kshin/T4SS_sim/PDB/test/template_files/T4SS_coord.txt"
num_stacks: 10
name: "T4SS"
num_cores: 12
# apix in nm
apix: 0.283
num_chimera_windows: 3
defocus_values: [1, 5, 10]
bead_map: "/data/kshin/T4SS_sim/bead.mrc"
email: "kshin@caltech.edu"

# Custom configs
custom_configs:
  membrane_path: "/data/kshin/T4SS_sim/PDB/pdb_maps/mem_chimera.mrc"
  orientations_tbl: "/data/kshin/T4SS_sim/manual_full.tbl"
  rod: "/data/kshin/T4SS_sim/PDB/pdb_maps/rod_chimera.mrc"
  barrel: "/data/kshin/T4SS_sim/PDB/pdb_maps/barrel_chimera.mrc"
