---
# Persistent configs
tem_simulator_executable: "/home/kshin/software/TEM-simulator_1.3/src/TEM-simulator"
chimera_exec_path: "/home/kshin/.local/UCSF-Chimera64-1.15rc/bin/chimera"

# Run-specific configs
model: "/home/kshin/repositories/ETSimulations/templates/tem_simulator/bead.mrc"
root: "/home/kshin/repositories/ETSimulations/test"
config: "/home/kshin/repositories/ETSimulations/templates/tem_simulator/sim.txt"
coord: "/home/kshin/repositories/ETSimulations/templates/tem_simulator/T4SS_coord.txt"
coord_error:
  mu: 0
  sigma: 50
num_stacks: 1
name: "Bead"
num_cores: 1
# apix in nm
apix: 0.283
num_chimera_windows: 1
defocus_values: [1]
bead_map: "/home/kshin/repositories/ETSimulations/templates/tem_simulator/bead.mrc"
bead_occupancy: 0.00025
assembler: "basic"
email: "kshin@caltech.edu"

# Custom configs
custom_configs:
  orientations_source: "gauss(0, 1)"
  use_common_model: true
