---
root: "/data/kshin/T4SS_sim/PDB/test_depths2"
name: "T4SS"
processors: [
#  {name: "eman2",
#   args:
#  {
#     steps_to_run: ["import", "reconstruct", "extract", "build_set"],
#     e2import_parameters : {
#      "import_tiltseries": "enable",
#      "importation": "copy",
#      "apix": 2.83,
#      "boxsize": 64
#    },
#    e2tomogram_parameters : {
#      "tltstep": 3,
#      "tltax": -90,
#      "npk": 10,
#      "tltkeep": 0.9,
#      "outsize": "1k",
#      "niter": "2,1,1,1",
#      "pkkeep": 0.9,
#      "bxsz": 64,
#      "pk_mindist": 0.125,
#      "filterto": 0.45,
#      "rmbeadthr": 10.0,
#      "threads": 12,
#      "clipz": 350,
#      "notmp": "enable"
#    },
#     e2spt_tomoctf_parameters : {
#      "alltiltseries": "enable",
#      "dfrange": "2.0,7.0,0.02",
#      "psrange": "0,5,5",
#      "tilesize": 256,
#      "voltage": 300,
#      "cs": 2.7,
#      "nref": 15,
#      "stepx": 20,
#      "stepy": 40,
#      "checkhand": "enable"
#    },
#    particle_coordinates_parameters: {
#      mode: "multiple",
#      coordinates_file: "T4SS_coords_3by3.txt",
#      unbinned_boxsize: 128,
#    },
#    e2spt_extract_parameters : {
#      "alltomograms": "enable",
#      "boxsz_unbin": 128,
#      "threads": 12,
#      "maxtilt": 100,
#      "padtwod": 2.0,
#      "shrink": 1,
#      "tltkeep": 1.0,
#      "rmbeadthr": 10.0
#    },
#    e2spt_buildsets_parameters : {
#      "allparticles": "enable"
#    },
#      e2spt_sgd_parameters : {
#      "sym": "c1",
#      "gaussz": -1.0,
#      "filterto": 0.02,
#      "fourier": "enable",
#      "batchsize": 12,
#      "learnrate": 0.1,
#      "niter": 5,
#      "nbatch": 10,
#      "shrink": 1
#    },
#    e2spt_refine_parameters : {
#      "niter": 5,
#      "sym": "c1",
#      "mass": 500,
#      "goldstandard": 70,
#      "pkeep": 1.0,
#      "maxtilt": 90,
#      "threads": 12
#    }
#    }
#  },
#{
# name: "imod",
# args: {
#   start_step: 0.0,
#   end_step: 8.0,
#   num_fiducials: 10,
#   tilt_axis: -90,
#   apix: 0.283,
#   fiducial_method: "autofidseed",
#   data_dirs_start_with: "T4SS",
#   reconstruction_method: "tomo3d",
#   flipyz: true,
#   binvol: {
#     "binning": 2
#   },
#   tomo3d_path: "tomo3d",
#   tomo3d_options: {
#     "S": "enable",
#     "z": 700
#   }
# }
#},
#{
#  name: "i3",
#  args: {
#    mraparam_path: "/Users/kshin/Documents/data/T4SS/cluster_041720/data_processors/processed_data/IMOD/T4SS_0/T4SS_0.tlt",
#    real_data_mode: false,
#    tlt_angle: -90.0
#  }
#},
#{
# name: "dynamo",
# args: {
#   box_size: 64,
#   num_workers: 12,
#   project_name: "t4ss",
#   real_data_mode: false,
#   source_type: "imod",
#   cores: 1,
#   mask: "path/to/mask",
#   mwa: 12,
#   ite_r1: 1,
#   cr_r1: 20,
#   cs_r1: 1,
#   ir_r1: 30,
#   is_r1: 1,
#   rff_r1: 2,
#   rf_r1: 5,
#   dim_r1: 64,
#   lim_r1: [10,10,10],
#   limm_r1: 1,
#   nref_r1: 1,
#   high_r1: 1,
#   low_r1: 18,
#   sym_r1: "c13",
#   dst: "matlab_gpu",
#   gpus: 0
# }
#}
{
 name: "artiatomi",
 args: {
   emsart_path: "/home/kshin/Documents/repositories/Artiatomi/build/EmSART",
   emsart_subvols_path: "/home/kshin/Documents/repositories/Artiatomi/build/EmSARTSubVols",
   real_data_mode: false,
   setup_reconstructions_and_motls: true,
   setup_averaging: true,
   setup_refinement: true,
   reconstruction_template_config: "/home/kshin/Documents/repositories/ETSimulations/templates/artiatomi/EmSART_HR.cfg",
   output_suffix: "_SART_HR_1k.em",
   tomogram_size_x: 1000,
   tomogram_size_y: 1000,
   tomogram_size_z: 350,
   position_binning: 2,
   box_size: 128,
   angIter: 10,
   angIncr: 0.1,
   phiAngIter: 10,
   phiAngIncr: 0.1,
   lowPass: 12,
   highPass: 0,
   sigma: 3
 }
}
]