name: Test ETSimulations

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test ETSimulations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install virtualenv
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          venv etsimulations_env
          source etsimulations_env/bin/activate
          pip install -r requirements.txt

      - name: Run tests
      - run: |
          cd src
          python -m pytest ../tests
