name: Test ETSimulations

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test ETSimulations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          cd src
          python -m pytest ../tests
